- name: Copy netca.rsp
  template:
    src: "{{ item }}"
    dest: "/opt/oracle/{{ item }}"
    owner: oracle
    group: oinstall
    mode: 0660
    backup: no
  with_items:
  - netca.rsp

- name: Setup listener
  shell: "ORACLE_HOME={{ oracle_home }} && \
          export ORACLE_HOME && \
          {{ oracle_home }}/bin/netca /silent /responsefile /opt/oracle/netca.rsp"
  become: yes
  become_user: oracle

